config/routes.rb
Rails.application.routes.draw do
  get 'access/new'
  get 'access/create'
  get 'access/destroy'
  get 'admin/index'
  resources :users
  resources :orders
  resources :lineitems
  resources :carts
  get 'shopper/index'
  resources :products

  get'/', to: "shopper#index"
  get'/shopper', to: "shopper#index"

  get '/admin', to: 'admin#index'
  get '/login', to: 'access#new'
  post '/access/new', to: 'access#create'
  delete '/logout', to: 'access#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App278</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 
  

  <body class='<%= controller.controller_name %>'>

  <div id="banner">
    <%= @page_title || "Our Products" %>
  </div>
  <div id="columns">
    <div id="side">
    <% if controller.controller_name == "shopper" %>
     <div id='cart'>
        <%= render @cart%>
      </div>  
     <% end %>
     
      <ul>
        <li><a href="/products">Products</a></li>
        <li><a href="/shopper">Shopper</a></li>
      </ul>
      <%= button_to 'Login', login_path, method: :get %>
      <% if session[:user_id] %>
        Hello, <%= User.find_by(id: session[:user_id]).name%>
        <ul>
          <li><%= link_to 'Orders',orders_path %></li>
          <li><%= link_to 'Products', products_path %></li>
          <li><%= link_to 'Users',    users_path    %></li>
        </ul>
        <%= button_to 'Logout', logout_path, method: :delete %> 
      <% end %>
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>
</body>
</html>